/*
 * generated by Xtext 2.12.0
 */
package nl.esi.poosl.xtext.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(PooslInjectorProvider)
class PooslParsingTest {

	@Test
	def void loadModel() {
		Assert.assertTrue(true)
	}
}
