/* ************************************************************************** *
 * Copyright (c) 2021 TNO/ESI
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *    TNO/ESI - initial API and implementation
 *    Obeo - refactoring
 * ************************************************************************* */
package org.eclipse.poosl.sirius.navigator;

import org.eclipse.osgi.util.NLS;

/**
 * Messages of org.eclipse.poosl.sirius.navigator.
 *
 * @author nperansin
 */
// CHECKSTYLE:OFF generated by Eclipse tool
public final class Messages extends NLS {
    private static final String BUNDLE_NAME = "org.eclipse.poosl.sirius.navigator.messages"; //$NON-NLS-1$

    public static String GPM_DIALOG_LABEL;
    static {
        // initialize resource bundle
        NLS.initializeMessages(BUNDLE_NAME, Messages.class);
    }

    private Messages() {
    }
}
