//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.20 at 03:57:25 PM CET 
//

package org.eclipse.poosl.generatedxmlclasses;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.eclipse.poosl.generatedxmlclasses package.
 * <p>
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TExecutiontreeSequential_QNAME = new QName("uri:poosl",
            "sequential");

    private final static QName _TExecutiontreeMethodCall_QNAME = new QName("uri:poosl",
            "method_call");

    private final static QName _TExecutiontreeParallel_QNAME = new QName("uri:poosl", "parallel");

    private final static QName _TExecutiontreeSelect_QNAME = new QName("uri:poosl", "select");

    private final static QName _TExecutiontreeStatement_QNAME = new QName("uri:poosl", "statement");

    private final static QName _TExecutiontreeExpression_QNAME = new QName("uri:poosl",
            "expression");

    private final static QName _TExecutiontreeProcessMethodCall_QNAME = new QName("uri:poosl",
            "process_method_call");

    private final static QName _TExecutiontreeMessageSend_QNAME = new QName("uri:poosl",
            "message_send");

    private final static QName _TExecutiontreeMessageReceive_QNAME = new QName("uri:poosl",
            "message_receive");

    private final static QName _TExecutiontreeGuard_QNAME = new QName("uri:poosl", "guard");

    private final static QName _TExecutiontreeWhile_QNAME = new QName("uri:poosl", "while");

    private final static QName _TExecutiontreeAbort_QNAME = new QName("uri:poosl", "abort");

    private final static QName _TExecutiontreeInterrupt_QNAME = new QName("uri:poosl", "interrupt");

    private final static QName _TExecutiontreeSkip_QNAME = new QName("uri:poosl", "skip");

    private final static QName _TExecutiontreeDelay_QNAME = new QName("uri:poosl", "delay");

    private final static QName _TExecutiontreeSequenceOfExpressions_QNAME = new QName("uri:poosl",
            "sequence_of_expressions");

    private final static QName _TExecutiontreeAssignment_QNAME = new QName("uri:poosl",
            "assignment");

    private final static QName _TExecutiontreeDataMethodCall_QNAME = new QName("uri:poosl",
            "data_method_call");

    private final static QName _TExecutiontreeConstant_QNAME = new QName("uri:poosl", "constant");

    private final static QName _TExecutiontreeVariable_QNAME = new QName("uri:poosl", "variable");

    private final static QName _TExecutiontreeBinaryOperation_QNAME = new QName("uri:poosl",
            "binary_operation");

    private final static QName _TExecutiontreeUnaryOperation_QNAME = new QName("uri:poosl",
            "unary_operation");

    private final static QName _TExecutiontreeSelf_QNAME = new QName("uri:poosl", "self");

    private final static QName _TExecutiontreeNil_QNAME = new QName("uri:poosl", "nil");

    private final static QName _TExecutiontreeCurrentTime_QNAME = new QName("uri:poosl",
            "current_time");

    private final static QName _TExecutiontreeIf_QNAME = new QName("uri:poosl", "if");

    private final static QName _TExecutiontreeNew_QNAME = new QName("uri:poosl", "new");

    private final static QName _TExecutiontreeReturn_QNAME = new QName("uri:poosl", "return");

    private final static QName _TExecutiontreeSwitch_QNAME = new QName("uri:poosl", "switch");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: org.eclipse.poosl.generatedxmlclasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TCommunicationEventParameter }
     * 
     */
    public TCommunicationEventParameter createTCommunicationEventParameter() {
        return new TCommunicationEventParameter();
    }

    /**
     * Create an instance of {@link TInspectSystem }
     * 
     */
    public TInspectSystem createTInspectSystem() {
        return new TInspectSystem();
    }

    /**
     * Create an instance of {@link TInspectCluster }
     * 
     */
    public TInspectCluster createTInspectCluster() {
        return new TInspectCluster();
    }

    /**
     * Create an instance of {@link TListFilesResponse }
     * 
     */
    public TListFilesResponse createTListFilesResponse() {
        return new TListFilesResponse();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link TLoadRequest }
     * 
     */
    public TLoadRequest createTLoadRequest() {
        return new TLoadRequest();
    }

    /**
     * Create an instance of {@link TCompileRequest }
     * 
     */
    public TCompileRequest createTCompileRequest() {
        return new TCompileRequest();
    }

    /**
     * Create an instance of {@link TListFilesRequest }
     * 
     */
    public TListFilesRequest createTListFilesRequest() {
        return new TListFilesRequest();
    }

    /**
     * Create an instance of {@link TListClassesRequest }
     * 
     */
    public TListClassesRequest createTListClassesRequest() {
        return new TListClassesRequest();
    }

    /**
     * Create an instance of {@link TGetTopLevelSpecificationRequest }
     * 
     */
    public TGetTopLevelSpecificationRequest createTGetTopLevelSpecificationRequest() {
        return new TGetTopLevelSpecificationRequest();
    }

    /**
     * Create an instance of {@link TInstantiateRequest }
     * 
     */
    public TInstantiateRequest createTInstantiateRequest() {
        return new TInstantiateRequest();
    }

    /**
     * Create an instance of {@link TCommandRequest }
     * 
     */
    public TCommandRequest createTCommandRequest() {
        return new TCommandRequest();
    }

    /**
     * Create an instance of {@link TExecutionStateRequest }
     * 
     */
    public TExecutionStateRequest createTExecutionStateRequest() {
        return new TExecutionStateRequest();
    }

    /**
     * Create an instance of {@link TGetTransitionsRequest }
     * 
     */
    public TGetTransitionsRequest createTGetTransitionsRequest() {
        return new TGetTransitionsRequest();
    }

    /**
     * Create an instance of {@link TPerformTransitionRequest }
     * 
     */
    public TPerformTransitionRequest createTPerformTransitionRequest() {
        return new TPerformTransitionRequest();
    }

    /**
     * Create an instance of {@link TPerformProcessStepRequest }
     * 
     */
    public TPerformProcessStepRequest createTPerformProcessStepRequest() {
        return new TPerformProcessStepRequest();
    }

    /**
     * Create an instance of {@link TInspectRequest }
     * 
     */
    public TInspectRequest createTInspectRequest() {
        return new TInspectRequest();
    }

    /**
     * Create an instance of {@link TCreateBreakpointRequest }
     * 
     */
    public TCreateBreakpointRequest createTCreateBreakpointRequest() {
        return new TCreateBreakpointRequest();
    }

    /**
     * Create an instance of {@link TEnableBreakpointRequest }
     * 
     */
    public TEnableBreakpointRequest createTEnableBreakpointRequest() {
        return new TEnableBreakpointRequest();
    }

    /**
     * Create an instance of {@link TDisableBreakpointRequest }
     * 
     */
    public TDisableBreakpointRequest createTDisableBreakpointRequest() {
        return new TDisableBreakpointRequest();
    }

    /**
     * Create an instance of {@link TDeleteBreakpointRequest }
     * 
     */
    public TDeleteBreakpointRequest createTDeleteBreakpointRequest() {
        return new TDeleteBreakpointRequest();
    }

    /**
     * Create an instance of {@link TSetVariableRequest }
     * 
     */
    public TSetVariableRequest createTSetVariableRequest() {
        return new TSetVariableRequest();
    }

    /**
     * Create an instance of {@link TGetPositionRequest }
     * 
     */
    public TGetPositionRequest createTGetPositionRequest() {
        return new TGetPositionRequest();
    }

    /**
     * Create an instance of {@link TEengineEventSetupRequest }
     * 
     */
    public TEengineEventSetupRequest createTEengineEventSetupRequest() {
        return new TEengineEventSetupRequest();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link TLoadResponse }
     * 
     */
    public TLoadResponse createTLoadResponse() {
        return new TLoadResponse();
    }

    /**
     * Create an instance of {@link TCompileResponse }
     * 
     */
    public TCompileResponse createTCompileResponse() {
        return new TCompileResponse();
    }

    /**
     * Create an instance of {@link TGetPositionResponse }
     * 
     */
    public TGetPositionResponse createTGetPositionResponse() {
        return new TGetPositionResponse();
    }

    /**
     * Create an instance of {@link TListClassesResponse }
     * 
     */
    public TListClassesResponse createTListClassesResponse() {
        return new TListClassesResponse();
    }

    /**
     * Create an instance of {@link TGetTopLevelSpecificationResponse }
     * 
     */
    public TGetTopLevelSpecificationResponse createTGetTopLevelSpecificationResponse() {
        return new TGetTopLevelSpecificationResponse();
    }

    /**
     * Create an instance of {@link TInstantiateResponse }
     * 
     */
    public TInstantiateResponse createTInstantiateResponse() {
        return new TInstantiateResponse();
    }

    /**
     * Create an instance of {@link TCommandResponse }
     * 
     */
    public TCommandResponse createTCommandResponse() {
        return new TCommandResponse();
    }

    /**
     * Create an instance of {@link TExecutionStateChangeResponse }
     * 
     */
    public TExecutionStateChangeResponse createTExecutionStateChangeResponse() {
        return new TExecutionStateChangeResponse();
    }

    /**
     * Create an instance of {@link TGetTransitionsResponse }
     * 
     */
    public TGetTransitionsResponse createTGetTransitionsResponse() {
        return new TGetTransitionsResponse();
    }

    /**
     * Create an instance of {@link TPerformTransitionResponse }
     * 
     */
    public TPerformTransitionResponse createTPerformTransitionResponse() {
        return new TPerformTransitionResponse();
    }

    /**
     * Create an instance of {@link TInspectResponse }
     * 
     */
    public TInspectResponse createTInspectResponse() {
        return new TInspectResponse();
    }

    /**
     * Create an instance of {@link TCreateBreakpointResponse }
     * 
     */
    public TCreateBreakpointResponse createTCreateBreakpointResponse() {
        return new TCreateBreakpointResponse();
    }

    /**
     * Create an instance of {@link TEnableBreakpointResponse }
     * 
     */
    public TEnableBreakpointResponse createTEnableBreakpointResponse() {
        return new TEnableBreakpointResponse();
    }

    /**
     * Create an instance of {@link TDisableBreakpointResponse }
     * 
     */
    public TDisableBreakpointResponse createTDisableBreakpointResponse() {
        return new TDisableBreakpointResponse();
    }

    /**
     * Create an instance of {@link TDeleteBreakpointResponse }
     * 
     */
    public TDeleteBreakpointResponse createTDeleteBreakpointResponse() {
        return new TDeleteBreakpointResponse();
    }

    /**
     * Create an instance of {@link TSetVariableResponse }
     * 
     */
    public TSetVariableResponse createTSetVariableResponse() {
        return new TSetVariableResponse();
    }

    /**
     * Create an instance of {@link TEengineEventSetupResponse }
     * 
     */
    public TEengineEventSetupResponse createTEengineEventSetupResponse() {
        return new TEengineEventSetupResponse();
    }

    /**
     * Create an instance of {@link TCommunicationEvent }
     * 
     */
    public TCommunicationEvent createTCommunicationEvent() {
        return new TCommunicationEvent();
    }

    /**
     * Create an instance of {@link TEengineEventErrorResponse }
     * 
     */
    public TEengineEventErrorResponse createTEengineEventErrorResponse() {
        return new TEengineEventErrorResponse();
    }

    /**
     * Create an instance of {@link THandle }
     * 
     */
    public THandle createTHandle() {
        return new THandle();
    }

    /**
     * Create an instance of {@link TSenderInfo }
     * 
     */
    public TSenderInfo createTSenderInfo() {
        return new TSenderInfo();
    }

    /**
     * Create an instance of {@link TReceiverInfo }
     * 
     */
    public TReceiverInfo createTReceiverInfo() {
        return new TReceiverInfo();
    }

    /**
     * Create an instance of {@link TTransition }
     * 
     */
    public TTransition createTTransition() {
        return new TTransition();
    }

    /**
     * Create an instance of {@link TCommunicationTransition }
     * 
     */
    public TCommunicationTransition createTCommunicationTransition() {
        return new TCommunicationTransition();
    }

    /**
     * Create an instance of {@link TProcessStepTransition }
     * 
     */
    public TProcessStepTransition createTProcessStepTransition() {
        return new TProcessStepTransition();
    }

    /**
     * Create an instance of {@link TDataStepTransition }
     * 
     */
    public TDataStepTransition createTDataStepTransition() {
        return new TDataStepTransition();
    }

    /**
     * Create an instance of {@link TDelayTransition }
     * 
     */
    public TDelayTransition createTDelayTransition() {
        return new TDelayTransition();
    }

    /**
     * Create an instance of {@link TTransitionList }
     * 
     */
    public TTransitionList createTTransitionList() {
        return new TTransitionList();
    }

    /**
     * Create an instance of {@link TSourcePosition }
     * 
     */
    public TSourcePosition createTSourcePosition() {
        return new TSourcePosition();
    }

    /**
     * Create an instance of {@link TInclude }
     * 
     */
    public TInclude createTInclude() {
        return new TInclude();
    }

    /**
     * Create an instance of {@link TInspectProcess }
     * 
     */
    public TInspectProcess createTInspectProcess() {
        return new TInspectProcess();
    }

    /**
     * Create an instance of {@link TInspectPort }
     * 
     */
    public TInspectPort createTInspectPort() {
        return new TInspectPort();
    }

    /**
     * Create an instance of {@link TInspectModel }
     * 
     */
    public TInspectModel createTInspectModel() {
        return new TInspectModel();
    }

    /**
     * Create an instance of {@link TInspectInstance }
     * 
     */
    public TInspectInstance createTInspectInstance() {
        return new TInspectInstance();
    }

    /**
     * Create an instance of {@link TInspectChannel }
     * 
     */
    public TInspectChannel createTInspectChannel() {
        return new TInspectChannel();
    }

    /**
     * Create an instance of {@link TStackframe }
     * 
     */
    public TStackframe createTStackframe() {
        return new TStackframe();
    }

    /**
     * Create an instance of {@link TInspectVariableContext }
     * 
     */
    public TInspectVariableContext createTInspectVariableContext() {
        return new TInspectVariableContext();
    }

    /**
     * Create an instance of {@link TInspectVariable }
     * 
     */
    public TInspectVariable createTInspectVariable() {
        return new TInspectVariable();
    }

    /**
     * Create an instance of {@link TInspectData }
     * 
     */
    public TInspectData createTInspectData() {
        return new TInspectData();
    }

    /**
     * Create an instance of {@link TInspectTransition }
     * 
     */
    public TInspectTransition createTInspectTransition() {
        return new TInspectTransition();
    }

    /**
     * Create an instance of {@link TCommuncationEventNode }
     * 
     */
    public TCommuncationEventNode createTCommuncationEventNode() {
        return new TCommuncationEventNode();
    }

    /**
     * Create an instance of {@link TErrorStacktrace }
     * 
     */
    public TErrorStacktrace createTErrorStacktrace() {
        return new TErrorStacktrace();
    }

    /**
     * Create an instance of {@link TErrorStackframe }
     * 
     */
    public TErrorStackframe createTErrorStackframe() {
        return new TErrorStackframe();
    }

    /**
     * Create an instance of {@link TCommunicationEventMessage }
     * 
     */
    public TCommunicationEventMessage createTCommunicationEventMessage() {
        return new TCommunicationEventMessage();
    }

    /**
     * Create an instance of {@link TBreakpoint }
     * 
     */
    public TBreakpoint createTBreakpoint() {
        return new TBreakpoint();
    }

    /**
     * Create an instance of {@link TBreakpointInfo }
     * 
     */
    public TBreakpointInfo createTBreakpointInfo() {
        return new TBreakpointInfo();
    }

    /**
     * Create an instance of {@link TErrorInfo }
     * 
     */
    public TErrorInfo createTErrorInfo() {
        return new TErrorInfo();
    }

    /**
     * Create an instance of {@link TVarList }
     * 
     */
    public TVarList createTVarList() {
        return new TVarList();
    }

    /**
     * Create an instance of {@link TVariable }
     * 
     */
    public TVariable createTVariable() {
        return new TVariable();
    }

    /**
     * Create an instance of {@link TSublist }
     * 
     */
    public TSublist createTSublist() {
        return new TSublist();
    }

    /**
     * Create an instance of {@link TMethod }
     * 
     */
    public TMethod createTMethod() {
        return new TMethod();
    }

    /**
     * Create an instance of {@link TExecutiontree }
     * 
     */
    public TExecutiontree createTExecutiontree() {
        return new TExecutiontree();
    }

    /**
     * Create an instance of {@link TExecutiontreeStatements }
     * 
     */
    public TExecutiontreeStatements createTExecutiontreeStatements() {
        return new TExecutiontreeStatements();
    }

    /**
     * Create an instance of {@link TExecutiontreeMethodCall }
     * 
     */
    public TExecutiontreeMethodCall createTExecutiontreeMethodCall() {
        return new TExecutiontreeMethodCall();
    }

    /**
     * Create an instance of {@link TExecutiontreeMessageSend }
     * 
     */
    public TExecutiontreeMessageSend createTExecutiontreeMessageSend() {
        return new TExecutiontreeMessageSend();
    }

    /**
     * Create an instance of {@link TExecutiontreeMessageReceive }
     * 
     */
    public TExecutiontreeMessageReceive createTExecutiontreeMessageReceive() {
        return new TExecutiontreeMessageReceive();
    }

    /**
     * Create an instance of {@link TExecutiontreeExpression }
     * 
     */
    public TExecutiontreeExpression createTExecutiontreeExpression() {
        return new TExecutiontreeExpression();
    }

    /**
     * Create an instance of {@link TExecutiontreeBase }
     * 
     */
    public TExecutiontreeBase createTExecutiontreeBase() {
        return new TExecutiontreeBase();
    }

    /**
     * Create an instance of {@link TCommunicationEventParameter.Parameter }
     * 
     */
    public TCommunicationEventParameter.Parameter createTCommunicationEventParameterParameter() {
        return new TCommunicationEventParameter.Parameter();
    }

    /**
     * Create an instance of {@link TInspectSystem.Channel }
     * 
     */
    public TInspectSystem.Channel createTInspectSystemChannel() {
        return new TInspectSystem.Channel();
    }

    /**
     * Create an instance of {@link TInspectCluster.Channel }
     * 
     */
    public TInspectCluster.Channel createTInspectClusterChannel() {
        return new TInspectCluster.Channel();
    }

    /**
     * Create an instance of {@link TListFilesResponse.File }
     * 
     */
    public TListFilesResponse.File createTListFilesResponseFile() {
        return new TListFilesResponse.File();
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeStatements }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeStatements }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "sequential", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeStatements> createTExecutiontreeSequential(
            TExecutiontreeStatements value) {
        return new JAXBElement<TExecutiontreeStatements>(_TExecutiontreeSequential_QNAME,
                TExecutiontreeStatements.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeMethodCall }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeMethodCall }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "method_call", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeMethodCall> createTExecutiontreeMethodCall(
            TExecutiontreeMethodCall value) {
        return new JAXBElement<TExecutiontreeMethodCall>(_TExecutiontreeMethodCall_QNAME,
                TExecutiontreeMethodCall.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeStatements }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeStatements }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "parallel", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeStatements> createTExecutiontreeParallel(
            TExecutiontreeStatements value) {
        return new JAXBElement<TExecutiontreeStatements>(_TExecutiontreeParallel_QNAME,
                TExecutiontreeStatements.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeStatements }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeStatements }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "select", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeStatements> createTExecutiontreeSelect(
            TExecutiontreeStatements value) {
        return new JAXBElement<TExecutiontreeStatements>(_TExecutiontreeSelect_QNAME,
                TExecutiontreeStatements.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "statement", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeStatement(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeStatement_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeExpression }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeExpression }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "expression", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeExpression> createTExecutiontreeExpression(
            TExecutiontreeExpression value) {
        return new JAXBElement<TExecutiontreeExpression>(_TExecutiontreeExpression_QNAME,
                TExecutiontreeExpression.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl",
            name = "process_method_call",
            scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeProcessMethodCall(
            TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeProcessMethodCall_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeMessageSend }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeMessageSend }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "message_send", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeMessageSend> createTExecutiontreeMessageSend(
            TExecutiontreeMessageSend value) {
        return new JAXBElement<TExecutiontreeMessageSend>(_TExecutiontreeMessageSend_QNAME,
                TExecutiontreeMessageSend.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeMessageReceive }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeMessageReceive }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "message_receive", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeMessageReceive> createTExecutiontreeMessageReceive(
            TExecutiontreeMessageReceive value) {
        return new JAXBElement<TExecutiontreeMessageReceive>(_TExecutiontreeMessageReceive_QNAME,
                TExecutiontreeMessageReceive.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "guard", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeGuard(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeGuard_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "while", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeWhile(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeWhile_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "abort", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeAbort(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeAbort_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "interrupt", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeInterrupt(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeInterrupt_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "skip", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeSkip(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeSkip_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "delay", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeDelay(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeDelay_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl",
            name = "sequence_of_expressions",
            scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeSequenceOfExpressions(
            TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeSequenceOfExpressions_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "assignment", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeAssignment(
            TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeAssignment_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl",
            name = "data_method_call",
            scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeDataMethodCall(
            TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeDataMethodCall_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "constant", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeConstant(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeConstant_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "variable", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeVariable(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeVariable_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl",
            name = "binary_operation",
            scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeBinaryOperation(
            TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeBinaryOperation_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "unary_operation", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeUnaryOperation(
            TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeUnaryOperation_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "self", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeSelf(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeSelf_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "nil", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeNil(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeNil_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "current_time", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeCurrentTime(
            TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeCurrentTime_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "if", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeIf(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeIf_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "new", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeNew(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeNew_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "return", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeReturn(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeReturn_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement
     * }{@code <}{@link TExecutiontreeBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement
     *     }{@code <}{@link TExecutiontreeBase }{@code >}
     */
    @XmlElementDecl(namespace = "uri:poosl", name = "switch", scope = TExecutiontree.class)
    public JAXBElement<TExecutiontreeBase> createTExecutiontreeSwitch(TExecutiontreeBase value) {
        return new JAXBElement<TExecutiontreeBase>(_TExecutiontreeSwitch_QNAME,
                TExecutiontreeBase.class, TExecutiontree.class, value);
    }

}
