//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.20 at 03:57:25 PM CET 
//

package org.eclipse.poosl.generatedxmlclasses;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for t_communication_event complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="t_communication_event"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="simulation_time" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="sender" type="{uri:poosl}t_communcation_event_node"/&gt;
 *         &lt;element name="receiver" type="{uri:poosl}t_communcation_event_node"/&gt;
 *         &lt;element name="message" type="{uri:poosl}t_communication_event_message"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_communication_event",
        propOrder = { "simulationTime", "sender", "receiver", "message" })
public class TCommunicationEvent {

    @XmlElement(name = "simulation_time", required = true)
    protected BigDecimal simulationTime;

    @XmlElement(required = true)
    protected TCommuncationEventNode sender;

    @XmlElement(required = true)
    protected TCommuncationEventNode receiver;

    @XmlElement(required = true)
    protected TCommunicationEventMessage message;

    /**
     * Gets the value of the simulationTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     * 
     */
    public BigDecimal getSimulationTime() {
        return simulationTime;
    }

    /**
     * Sets the value of the simulationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     * 
     */
    public void setSimulationTime(BigDecimal value) {
        this.simulationTime = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link TCommuncationEventNode }
     * 
     */
    public TCommuncationEventNode getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCommuncationEventNode }
     * 
     */
    public void setSender(TCommuncationEventNode value) {
        this.sender = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link TCommuncationEventNode }
     * 
     */
    public TCommuncationEventNode getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCommuncationEventNode }
     * 
     */
    public void setReceiver(TCommuncationEventNode value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link TCommunicationEventMessage }
     * 
     */
    public TCommunicationEventMessage getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCommunicationEventMessage }
     * 
     */
    public void setMessage(TCommunicationEventMessage value) {
        this.message = value;
    }

}
