//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.20 at 03:57:25 PM CET 
//

package org.eclipse.poosl.generatedxmlclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for t_inspect_system complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="t_inspect_system"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="channel" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="output_port" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="instance" type="{uri:poosl}t_inspect_instance" maxOccurs="unbounded"/&gt;
 *         &lt;element name="port" type="{uri:poosl}t_inspect_port" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="execution_tree" type="{uri:poosl}t_executiontree"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_inspect_system", propOrder = { "channel", "instance", "port", "executionTree" })
public class TInspectSystem {

    protected List<TInspectSystem.Channel> channel;

    @XmlElement(required = true)
    protected List<TInspectInstance> instance;

    protected List<TInspectPort> port;

    @XmlElement(name = "execution_tree", required = true)
    protected TExecutiontree executionTree;

    /**
     * Gets the value of the channel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channel
     * property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getChannel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInspectSystem.Channel }
     * 
     * 
     */
    public List<TInspectSystem.Channel> getChannel() {
        if (channel == null) {
            channel = new ArrayList<TInspectSystem.Channel>();
        }
        return this.channel;
    }

    /**
     * Gets the value of the instance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instance
     * property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInspectInstance }
     * 
     * 
     */
    public List<TInspectInstance> getInstance() {
        if (instance == null) {
            instance = new ArrayList<TInspectInstance>();
        }
        return this.instance;
    }

    /**
     * Gets the value of the port property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the port property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPort().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInspectPort }
     * 
     * 
     */
    public List<TInspectPort> getPort() {
        if (port == null) {
            port = new ArrayList<TInspectPort>();
        }
        return this.port;
    }

    /**
     * Gets the value of the executionTree property.
     * 
     * @return
     *     possible object is
     *     {@link TExecutiontree }
     * 
     */
    public TExecutiontree getExecutionTree() {
        return executionTree;
    }

    /**
     * Sets the value of the executionTree property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExecutiontree }
     * 
     */
    public void setExecutionTree(TExecutiontree value) {
        this.executionTree = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="output_port" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Channel {

        @XmlAttribute(name = "name", required = true)
        protected String name;

        @XmlAttribute(name = "output_port")
        protected String outputPort;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         * 
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         * 
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the outputPort property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         * 
         */
        public String getOutputPort() {
            return outputPort;
        }

        /**
         * Sets the value of the outputPort property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         * 
         */
        public void setOutputPort(String value) {
            this.outputPort = value;
        }

    }

}
