//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.20 at 03:57:25 PM CET 
//

package org.eclipse.poosl.generatedxmlclasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for t_object_query_result.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="t_object_query_result"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ok"/&gt;
 *     &lt;enumeration value="unknown object"/&gt;
 *     &lt;enumeration value="unknown handle"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "t_object_query_result")
@XmlEnum
public enum TObjectQueryResult {

    @XmlEnumValue("ok")
    OK("ok"), @XmlEnumValue("unknown object")
    UNKNOWN_OBJECT("unknown object"), @XmlEnumValue("unknown handle")
    UNKNOWN_HANDLE("unknown handle");

    private final String value;

    TObjectQueryResult(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TObjectQueryResult fromValue(String v) {
        for (TObjectQueryResult c : TObjectQueryResult.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
