//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.20 at 03:57:25 PM CET 
//

package org.eclipse.poosl.generatedxmlclasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for t_set_variable_result.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="t_set_variable_result"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="unknown"/&gt;
 *     &lt;enumeration value="ok"/&gt;
 *     &lt;enumeration value="error"/&gt;
 *     &lt;enumeration value="invalid_var_handle"/&gt;
 *     &lt;enumeration value="invalid_list_handle"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "t_set_variable_result")
@XmlEnum
public enum TSetVariableResult {

    @XmlEnumValue("unknown")
    UNKNOWN("unknown"), @XmlEnumValue("ok")
    OK("ok"), @XmlEnumValue("error")
    ERROR("error"), @XmlEnumValue("invalid_var_handle")
    INVALID_VAR_HANDLE("invalid_var_handle"), @XmlEnumValue("invalid_list_handle")
    INVALID_LIST_HANDLE("invalid_list_handle");

    private final String value;

    TSetVariableResult(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TSetVariableResult fromValue(String v) {
        for (TSetVariableResult c : TSetVariableResult.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
