[link=https://github.com/eclipse/poosl/actions/workflows/maven.yml]
image::https://github.com/eclipse/poosl/workflows/Java%20CI/badge.svg[gh-actions status]

= Brief introduction to the POOSL project

The Parallel Object-Oriented Specification Language (POOSL) is a very expressive language to model 
concurrent hardware/software systems. POOSL has a small set of powerful primitives and it has an 
unambiguous formal semantics in terms of mathematical axioms and rules. POOSL models can be 
simulated with the Rotalumis simulator. 

This project provides an Eclipse-based tool for editing and debugging POOSL models.

== How to install
https://raw.githubusercontent.com/eclipse/poosl/main/docs/User/InstallationManual.pdf[Installation guide] 
helps you to install Eclipse and POOSL features.


== How to download Eclipse Features

Update site and help are accessible on https://eclipse.github.io/poosl[gh-pages site].


== How to build

Here you will find a introduction how to setup, build and run tests.

=== Preconditions

We assume the following tools/frameworks are available

- JDK 11 (JDK 16 or above is not supported for now)
- Maven 3.5+
- rcptt ide: is the IDE for RCPTT development 
- rcptt runner 2.5.0: is the command line tool for RCPTT 
- ${POOSL_SRC} stands for the poosl source location on your host

=== Command
To build the poosl project via maven you have to go run the following commands.

[source]
----
cd ${POOSL_SRC}
mvn clean verify
----

Executing this command will build the plugins, features, updatesite and products.

=== Locations
Update site is available at __${POOSL_SRC}/releng/org.eclipse.poosl.update/target/repository__
Product are available at __${POOSL_SRC}/releng/org.eclipse.poosl.product/target/products__

== Developing

Development guidelines are described at https://github.com/eclipse/poosl/tree/main/docs/Developer[org.eclipse.poosl.docs/Developer/readme.adoc]

=== Development environment

With Eclipse instal, use following Oomph setup to have a proper tool set (in Advanced mode).

[source]
----
https://raw.githubusercontent.com/eclipse/poosl/main/parent/oomph/org.eclipse.setup
----

Once the repository is cloned, following preferences should be set:

- *Java/Code style/Formatter*: import _org.eclipse.poosl.parent/preferences/JavaFormatter.xml_
- *Java/Code style/Clean Up*: import _org.eclipse.poosl.parent/preferences/CleanupProfile.xml_
- *Java/Code style/Code Templates*: import _/org.eclipse.poosl.parent/preferences/java-codetemplates.xml_

=== Contributing

- Create an github issue to describe the feature to add/fix.

- Fork the project in your github account and push your code.+
Commit must start with '[#<issue-number>] ' tag.

- Create a pull-request

- Wait for team review: a feedback will be provided or the commit will be merged.


== Automatic Tests via RCPTT

- In Eclipse environment, all tests are grouped in __org.eclipse.poosl.rcptt.allinone/AllTests.suite__

- In bash mode, use maven command:

[source,bash]
----
cd ${POOSL_SRC}
mvn verify -P integration-tests
----



