/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.poosl.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.poosl.xtext.parser.antlr.internal.InternalPooslParser;
import org.eclipse.poosl.xtext.services.PooslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PooslParser extends AbstractAntlrParser {

	@Inject
	private PooslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPooslParser createParser(XtextTokenStream stream) {
		return new InternalPooslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Poosl";
	}

	public PooslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PooslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
