= Samples

In addition to the https://github.com/eclipse/poosl/tree/main/plugins/org.eclipse.poosl.ide.examples/content[main POOSL examples and libraries], this folder contains an https://github.com/eclipse/poosl/tree/main/docs/samples/org.eclipse.poosl.user-contributions/[Eclipse project with samples] that have been contributed by users over time.

== Usage

To use any of these samples, you can simply copy the files into a POOSL project (using Eclipse POOSL). To get the files from github, open the file page then click on the "raw" button. You can then save the file from your browser.

Alternatively, clone or download the full https://github.com/eclipse/poosl[repository], and import the user-contributions project within Eclipse POOSL, using the "File > Import... > Existing Projects into Workspace" Wizard.

== How to contribute

Additional user contributions are very welcome: feel free to open a https://github.com/eclipse/poosl/pulls[pull request] containing your samples. It will be reviewed by the POOSL team and integrated into this page.
