= POOSL User contributions

This folder contains POOSL examples and libraries that have been contributed over time. They are not maintained and could require adaptations.

* https://github.com/eclipse/poosl/tree/main/docs/samples/org.eclipse.poosl.user-contributions/examples/JsonRPCExample[JSON-RPC Example], an example showing how to call methods written in Python or Java from POOSL using remote procedure calls (RPC) based on JSON-RPC.
* https://github.com/eclipse/poosl/tree/main/docs/samples/org.eclipse.poosl.user-contributions/libraries[A set of libraries], to manipulate vectors, matrix, state machines, XML.

= Usage

To integrate any of the examples presented here, you can simply copy the .poosl files into a POOSL project (using the POOSL IDE). To get the .poosl file from github, open the file page then click on the "raw" button. You can then save the .poosl file from your browser.

= How to contribute

Contributions are very welcomed, if you think your code could be a good addition for POOSL, feel free to open a pull request containing your samples. It will be reviewed by the POOSL team and integrated into this page.
