/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.poosl.xtext.ide;

import org.eclipse.poosl.xtext.ide.AbstractPooslIdeModule;

/**
 * Use this class to register ide components.
 */
public class PooslIdeModule extends AbstractPooslIdeModule {
}
