/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.poosl.xtext.ide;

/**
 * Use this class to register ide components.
 * 
 * @author <a href="mailto:arjan.mooij@tno.nl">Arjan Mooij</a>
 */
public class PooslIdeModule extends AbstractPooslIdeModule {
    // bla
}
