//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:04:04 AM CET 
//


package nl.esi.poosl.generatedxmlclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_channel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_channel">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:poosl}t_channel_internal">
 *       &lt;attribute name="output_port" type="{uri:poosl}t_identifier" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_channel")
public class TChannel
    extends TChannelInternal
{

    @XmlAttribute(name = "output_port")
    protected String outputPort;

    /**
     * Gets the value of the outputPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputPort() {
        return outputPort;
    }

    /**
     * Sets the value of the outputPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputPort(String value) {
        this.outputPort = value;
    }

}
