//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:04:04 AM CET 
//


package nl.esi.poosl.generatedxmlclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_cluster_class complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_cluster_class">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="interface" type="{uri:poosl}t_cluster_interface"/>
 *         &lt;element name="instantiation_parameter" type="{uri:poosl}t_typed_variable" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="channel" type="{uri:poosl}t_channel" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="instance" type="{uri:poosl}t_instance" maxOccurs="unbounded"/>
 *         &lt;element name="annotation" type="{uri:poosl}t_cluster_class_annotation" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{uri:poosl}t_poosl_type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_cluster_class", propOrder = {
    "_interface",
    "instantiationParameter",
    "channel",
    "instance",
    "annotation"
})
public class TClusterClass {

    @XmlElement(name = "interface", required = true)
    protected TClusterInterface _interface;
    @XmlElement(name = "instantiation_parameter")
    protected List<TTypedVariable> instantiationParameter;
    protected List<TChannel> channel;
    @XmlElement(required = true)
    protected List<TInstance> instance;
    protected TClusterClassAnnotation annotation;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the interface property.
     * 
     * @return
     *     possible object is
     *     {@link TClusterInterface }
     *     
     */
    public TClusterInterface getInterface() {
        return _interface;
    }

    /**
     * Sets the value of the interface property.
     * 
     * @param value
     *     allowed object is
     *     {@link TClusterInterface }
     *     
     */
    public void setInterface(TClusterInterface value) {
        this._interface = value;
    }

    /**
     * Gets the value of the instantiationParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instantiationParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstantiationParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTypedVariable }
     * 
     * 
     */
    public List<TTypedVariable> getInstantiationParameter() {
        if (instantiationParameter == null) {
            instantiationParameter = new ArrayList<TTypedVariable>();
        }
        return this.instantiationParameter;
    }

    /**
     * Gets the value of the channel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TChannel }
     * 
     * 
     */
    public List<TChannel> getChannel() {
        if (channel == null) {
            channel = new ArrayList<TChannel>();
        }
        return this.channel;
    }

    /**
     * Gets the value of the instance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInstance }
     * 
     * 
     */
    public List<TInstance> getInstance() {
        if (instance == null) {
            instance = new ArrayList<TInstance>();
        }
        return this.instance;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * @return
     *     possible object is
     *     {@link TClusterClassAnnotation }
     *     
     */
    public TClusterClassAnnotation getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TClusterClassAnnotation }
     *     
     */
    public void setAnnotation(TClusterClassAnnotation value) {
        this.annotation = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
