//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:04:04 AM CET 
//


package nl.esi.poosl.generatedxmlclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_compile_request complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_compile_request">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="basic_classes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="poosl_specification" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="cluster_class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="process_class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="data_class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="initial_method_call" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="process_method" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="data_method" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="expression" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *         &lt;element name="includes" type="{uri:poosl}t_include"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_compile_request", propOrder = {
    "basicClasses",
    "pooslSpecification",
    "clusterClass",
    "processClass",
    "dataClass",
    "initialMethodCall",
    "processMethod",
    "dataMethod",
    "expression",
    "includes"
})
public class TCompileRequest {

    @XmlElement(name = "basic_classes")
    protected String basicClasses;
    @XmlElement(name = "poosl_specification")
    protected String pooslSpecification;
    @XmlElement(name = "cluster_class")
    protected String clusterClass;
    @XmlElement(name = "process_class")
    protected String processClass;
    @XmlElement(name = "data_class")
    protected String dataClass;
    @XmlElement(name = "initial_method_call")
    protected String initialMethodCall;
    @XmlElement(name = "process_method")
    protected String processMethod;
    @XmlElement(name = "data_method")
    protected String dataMethod;
    protected String expression;
    @XmlElement(required = true)
    protected TInclude includes;

    /**
     * Gets the value of the basicClasses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasicClasses() {
        return basicClasses;
    }

    /**
     * Sets the value of the basicClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasicClasses(String value) {
        this.basicClasses = value;
    }

    /**
     * Gets the value of the pooslSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPooslSpecification() {
        return pooslSpecification;
    }

    /**
     * Sets the value of the pooslSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPooslSpecification(String value) {
        this.pooslSpecification = value;
    }

    /**
     * Gets the value of the clusterClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClusterClass() {
        return clusterClass;
    }

    /**
     * Sets the value of the clusterClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClusterClass(String value) {
        this.clusterClass = value;
    }

    /**
     * Gets the value of the processClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessClass() {
        return processClass;
    }

    /**
     * Sets the value of the processClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessClass(String value) {
        this.processClass = value;
    }

    /**
     * Gets the value of the dataClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataClass() {
        return dataClass;
    }

    /**
     * Sets the value of the dataClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataClass(String value) {
        this.dataClass = value;
    }

    /**
     * Gets the value of the initialMethodCall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialMethodCall() {
        return initialMethodCall;
    }

    /**
     * Sets the value of the initialMethodCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialMethodCall(String value) {
        this.initialMethodCall = value;
    }

    /**
     * Gets the value of the processMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessMethod() {
        return processMethod;
    }

    /**
     * Sets the value of the processMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessMethod(String value) {
        this.processMethod = value;
    }

    /**
     * Gets the value of the dataMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataMethod() {
        return dataMethod;
    }

    /**
     * Sets the value of the dataMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataMethod(String value) {
        this.dataMethod = value;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpression(String value) {
        this.expression = value;
    }

    /**
     * Gets the value of the includes property.
     * 
     * @return
     *     possible object is
     *     {@link TInclude }
     *     
     */
    public TInclude getIncludes() {
        return includes;
    }

    /**
     * Sets the value of the includes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInclude }
     *     
     */
    public void setIncludes(TInclude value) {
        this.includes = value;
    }

}
