//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:04:04 AM CET 
//


package nl.esi.poosl.generatedxmlclasses;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_communication_transition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_communication_transition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sender" type="{uri:poosl}t_sender_info"/>
 *         &lt;element name="receiver" type="{uri:poosl}t_receiver_info"/>
 *       &lt;/sequence>
 *       &lt;attribute name="handle" use="required" type="{uri:poosl}t_handle_id" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_communication_transition", propOrder = {
    "sender",
    "receiver"
})
public class TCommunicationTransition {

    @XmlElement(required = true)
    protected TSenderInfo sender;
    @XmlElement(required = true)
    protected TReceiverInfo receiver;
    @XmlAttribute(name = "handle", required = true)
    protected BigInteger handle;

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link TSenderInfo }
     *     
     */
    public TSenderInfo getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSenderInfo }
     *     
     */
    public void setSender(TSenderInfo value) {
        this.sender = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link TReceiverInfo }
     *     
     */
    public TReceiverInfo getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link TReceiverInfo }
     *     
     */
    public void setReceiver(TReceiverInfo value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the handle property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHandle() {
        return handle;
    }

    /**
     * Sets the value of the handle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHandle(BigInteger value) {
        this.handle = value;
    }

}
