//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:04:04 AM CET 
//


package nl.esi.poosl.generatedxmlclasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_command_result.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="t_command_result">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ok"/>
 *     &lt;enumeration value="no design loaded"/>
 *     &lt;enumeration value="breakpoint hit"/>
 *     &lt;enumeration value="error"/>
 *     &lt;enumeration value="unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "t_command_result")
@XmlEnum
public enum TCommandResult {

    @XmlEnumValue("ok")
    OK("ok"),
    @XmlEnumValue("no design loaded")
    NO_DESIGN_LOADED("no design loaded"),
    @XmlEnumValue("breakpoint hit")
    BREAKPOINT_HIT("breakpoint hit"),
    @XmlEnumValue("error")
    ERROR("error"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    TCommandResult(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TCommandResult fromValue(String v) {
        for (TCommandResult c: TCommandResult.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
