//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:04:04 AM CET 
//


package nl.esi.poosl.generatedxmlclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_expression complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_expression">
 *   &lt;complexContent>
 *     &lt;restriction base="{uri:poosl}t_expressions">
 *       &lt;choice>
 *         &lt;element name="sequence_of_expressions" type="{uri:poosl}t_expressions"/>
 *         &lt;element name="assignment" type="{uri:poosl}t_assignment"/>
 *         &lt;element name="data_method_call" type="{uri:poosl}t_data_method_call"/>
 *         &lt;element name="constant" type="{uri:poosl}t_constant"/>
 *         &lt;element name="variable" type="{uri:poosl}t_variable_ref"/>
 *         &lt;element name="binary_operation" type="{uri:poosl}t_binary_operation"/>
 *         &lt;element name="unary_operation" type="{uri:poosl}t_unary_operation"/>
 *         &lt;element name="self" type="{uri:poosl}t_empty"/>
 *         &lt;element name="nil" type="{uri:poosl}t_empty"/>
 *         &lt;element name="current_time" type="{uri:poosl}t_current_time"/>
 *         &lt;element name="if" type="{uri:poosl}t_if_expression"/>
 *         &lt;element name="while" type="{uri:poosl}t_while_expression"/>
 *         &lt;element name="switch" type="{uri:poosl}t_switch_expression"/>
 *         &lt;element name="new" type="{uri:poosl}t_object_creation"/>
 *         &lt;element name="return" type="{uri:poosl}t_expression"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_expression")
@XmlSeeAlso({
    TAssignment.class
})
public class TExpression
    extends TExpressions
{


}
