//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:04:04 AM CET 
//


package nl.esi.poosl.generatedxmlclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_expressions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_expressions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="sequence_of_expressions" type="{uri:poosl}t_expressions"/>
 *         &lt;element name="assignment" type="{uri:poosl}t_assignment"/>
 *         &lt;element name="data_method_call" type="{uri:poosl}t_data_method_call"/>
 *         &lt;element name="constant" type="{uri:poosl}t_constant"/>
 *         &lt;element name="variable" type="{uri:poosl}t_variable_ref"/>
 *         &lt;element name="binary_operation" type="{uri:poosl}t_binary_operation"/>
 *         &lt;element name="unary_operation" type="{uri:poosl}t_unary_operation"/>
 *         &lt;element name="self" type="{uri:poosl}t_empty"/>
 *         &lt;element name="nil" type="{uri:poosl}t_empty"/>
 *         &lt;element name="current_time" type="{uri:poosl}t_current_time"/>
 *         &lt;element name="if" type="{uri:poosl}t_if_expression"/>
 *         &lt;element name="while" type="{uri:poosl}t_while_expression"/>
 *         &lt;element name="switch" type="{uri:poosl}t_switch_expression"/>
 *         &lt;element name="new" type="{uri:poosl}t_object_creation"/>
 *         &lt;element name="return" type="{uri:poosl}t_expression"/>
 *       &lt;/choice>
 *       &lt;attribute name="stmt_handle" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_expressions", propOrder = {
    "sequenceOfExpressionsOrAssignmentOrDataMethodCall"
})
@XmlSeeAlso({
    TExpression.class
})
public class TExpressions {

    @XmlElementRefs({
        @XmlElementRef(name = "sequence_of_expressions", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "assignment", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "nil", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "constant", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "binary_operation", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "if", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "unary_operation", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "variable", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "self", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "new", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "while", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "switch", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "data_method_call", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "current_time", namespace = "uri:poosl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "return", namespace = "uri:poosl", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> sequenceOfExpressionsOrAssignmentOrDataMethodCall;
    @XmlAttribute(name = "stmt_handle")
    protected Integer stmtHandle;

    /**
     * Gets the value of the sequenceOfExpressionsOrAssignmentOrDataMethodCall property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sequenceOfExpressionsOrAssignmentOrDataMethodCall property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSequenceOfExpressionsOrAssignmentOrDataMethodCall().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TExpressions }{@code >}
     * {@link JAXBElement }{@code <}{@link TAssignment }{@code >}
     * {@link JAXBElement }{@code <}{@link TEmpty }{@code >}
     * {@link JAXBElement }{@code <}{@link TConstant }{@code >}
     * {@link JAXBElement }{@code <}{@link TBinaryOperation }{@code >}
     * {@link JAXBElement }{@code <}{@link TIfExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TUnaryOperation }{@code >}
     * {@link JAXBElement }{@code <}{@link TVariableRef }{@code >}
     * {@link JAXBElement }{@code <}{@link TEmpty }{@code >}
     * {@link JAXBElement }{@code <}{@link TObjectCreation }{@code >}
     * {@link JAXBElement }{@code <}{@link TWhileExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TSwitchExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TDataMethodCall }{@code >}
     * {@link JAXBElement }{@code <}{@link TCurrentTime }{@code >}
     * {@link JAXBElement }{@code <}{@link TExpression }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getSequenceOfExpressionsOrAssignmentOrDataMethodCall() {
        if (sequenceOfExpressionsOrAssignmentOrDataMethodCall == null) {
            sequenceOfExpressionsOrAssignmentOrDataMethodCall = new ArrayList<JAXBElement<?>>();
        }
        return this.sequenceOfExpressionsOrAssignmentOrDataMethodCall;
    }

    /**
     * Gets the value of the stmtHandle property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStmtHandle() {
        return stmtHandle;
    }

    /**
     * Sets the value of the stmtHandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStmtHandle(Integer value) {
        this.stmtHandle = value;
    }

}
