//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:04:04 AM CET 
//


package nl.esi.poosl.generatedxmlclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_initial_method_call complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_initial_method_call">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="method_call_text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="process_method_call" type="{uri:poosl}t_initial_process_method_call"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_initial_method_call", propOrder = {
    "methodCallText",
    "processMethodCall"
})
public class TInitialMethodCall {

    @XmlElement(name = "method_call_text")
    protected String methodCallText;
    @XmlElement(name = "process_method_call", required = true)
    protected TInitialProcessMethodCall processMethodCall;

    /**
     * Gets the value of the methodCallText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodCallText() {
        return methodCallText;
    }

    /**
     * Sets the value of the methodCallText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodCallText(String value) {
        this.methodCallText = value;
    }

    /**
     * Gets the value of the processMethodCall property.
     * 
     * @return
     *     possible object is
     *     {@link TInitialProcessMethodCall }
     *     
     */
    public TInitialProcessMethodCall getProcessMethodCall() {
        return processMethodCall;
    }

    /**
     * Sets the value of the processMethodCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInitialProcessMethodCall }
     *     
     */
    public void setProcessMethodCall(TInitialProcessMethodCall value) {
        this.processMethodCall = value;
    }

}
