//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:04:04 AM CET 
//


package nl.esi.poosl.generatedxmlclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_initial_process_method_call complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_initial_process_method_call">
 *   &lt;complexContent>
 *     &lt;restriction base="{uri:poosl}t_process_method_call">
 *       &lt;sequence>
 *         &lt;element name="argument" type="{uri:poosl}t_expression" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="return_variable" type="{uri:poosl}t_variable_name" maxOccurs="0" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="method_name" use="required" type="{uri:poosl}t_method_name" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_initial_process_method_call")
public class TInitialProcessMethodCall
    extends TProcessMethodCall
{


}
