//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:04:04 AM CET 
//


package nl.esi.poosl.generatedxmlclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_inspect_process complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_inspect_process">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="instance_variables" type="{uri:poosl}t_var_list"/>
 *         &lt;element name="execution_tree" type="{uri:poosl}t_executiontree"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_inspect_process", propOrder = {
    "instanceVariables",
    "executionTree"
})
public class TInspectProcess {

    @XmlElement(name = "instance_variables", required = true)
    protected TVarList instanceVariables;
    @XmlElement(name = "execution_tree", required = true)
    protected TExecutiontree executionTree;

    /**
     * Gets the value of the instanceVariables property.
     * 
     * @return
     *     possible object is
     *     {@link TVarList }
     *     
     */
    public TVarList getInstanceVariables() {
        return instanceVariables;
    }

    /**
     * Sets the value of the instanceVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVarList }
     *     
     */
    public void setInstanceVariables(TVarList value) {
        this.instanceVariables = value;
    }

    /**
     * Gets the value of the executionTree property.
     * 
     * @return
     *     possible object is
     *     {@link TExecutiontree }
     *     
     */
    public TExecutiontree getExecutionTree() {
        return executionTree;
    }

    /**
     * Sets the value of the executionTree property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExecutiontree }
     *     
     */
    public void setExecutionTree(TExecutiontree value) {
        this.executionTree = value;
    }

}
