//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:04:04 AM CET 
//


package nl.esi.poosl.generatedxmlclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_inspect_port complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_inspect_port">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="up_channel" type="{uri:poosl}t_inspect_channel" minOccurs="0"/>
 *         &lt;element name="down_channel" type="{uri:poosl}t_inspect_channel" minOccurs="0"/>
 *         &lt;element name="is_root" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_inspect_port", propOrder = {
    "name",
    "upChannel",
    "downChannel",
    "isRoot"
})
public class TInspectPort {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "up_channel")
    protected TInspectChannel upChannel;
    @XmlElement(name = "down_channel")
    protected TInspectChannel downChannel;
    @XmlElement(name = "is_root")
    protected boolean isRoot;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the upChannel property.
     * 
     * @return
     *     possible object is
     *     {@link TInspectChannel }
     *     
     */
    public TInspectChannel getUpChannel() {
        return upChannel;
    }

    /**
     * Sets the value of the upChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInspectChannel }
     *     
     */
    public void setUpChannel(TInspectChannel value) {
        this.upChannel = value;
    }

    /**
     * Gets the value of the downChannel property.
     * 
     * @return
     *     possible object is
     *     {@link TInspectChannel }
     *     
     */
    public TInspectChannel getDownChannel() {
        return downChannel;
    }

    /**
     * Sets the value of the downChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInspectChannel }
     *     
     */
    public void setDownChannel(TInspectChannel value) {
        this.downChannel = value;
    }

    /**
     * Gets the value of the isRoot property.
     * 
     */
    public boolean isIsRoot() {
        return isRoot;
    }

    /**
     * Sets the value of the isRoot property.
     * 
     */
    public void setIsRoot(boolean value) {
        this.isRoot = value;
    }

}
