//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:04:04 AM CET 
//


package nl.esi.poosl.generatedxmlclasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_object_query_result.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="t_object_query_result">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ok"/>
 *     &lt;enumeration value="unknown object"/>
 *     &lt;enumeration value="unknown handle"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "t_object_query_result")
@XmlEnum
public enum TObjectQueryResult {

    @XmlEnumValue("ok")
    OK("ok"),
    @XmlEnumValue("unknown object")
    UNKNOWN_OBJECT("unknown object"),
    @XmlEnumValue("unknown handle")
    UNKNOWN_HANDLE("unknown handle");
    private final String value;

    TObjectQueryResult(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TObjectQueryResult fromValue(String v) {
        for (TObjectQueryResult c: TObjectQueryResult.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
