//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.16 at 11:04:04 AM CET 
//


package nl.esi.poosl.generatedxmlclasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_process_method complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_process_method">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="argument" type="{uri:poosl}t_typed_variable" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="output_parameter" type="{uri:poosl}t_typed_variable" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="local_variable" type="{uri:poosl}t_typed_variable" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="body_text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="body_statement" type="{uri:poosl}t_statement"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{uri:poosl}t_identifier" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_process_method", propOrder = {
    "argument",
    "outputParameter",
    "localVariable",
    "bodyText",
    "bodyStatement"
})
public class TProcessMethod {

    protected List<TTypedVariable> argument;
    @XmlElement(name = "output_parameter")
    protected List<TTypedVariable> outputParameter;
    @XmlElement(name = "local_variable")
    protected List<TTypedVariable> localVariable;
    @XmlElement(name = "body_text")
    protected String bodyText;
    @XmlElement(name = "body_statement", required = true)
    protected TStatement bodyStatement;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the argument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the argument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArgument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTypedVariable }
     * 
     * 
     */
    public List<TTypedVariable> getArgument() {
        if (argument == null) {
            argument = new ArrayList<TTypedVariable>();
        }
        return this.argument;
    }

    /**
     * Gets the value of the outputParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTypedVariable }
     * 
     * 
     */
    public List<TTypedVariable> getOutputParameter() {
        if (outputParameter == null) {
            outputParameter = new ArrayList<TTypedVariable>();
        }
        return this.outputParameter;
    }

    /**
     * Gets the value of the localVariable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localVariable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalVariable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TTypedVariable }
     * 
     * 
     */
    public List<TTypedVariable> getLocalVariable() {
        if (localVariable == null) {
            localVariable = new ArrayList<TTypedVariable>();
        }
        return this.localVariable;
    }

    /**
     * Gets the value of the bodyText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBodyText() {
        return bodyText;
    }

    /**
     * Sets the value of the bodyText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBodyText(String value) {
        this.bodyText = value;
    }

    /**
     * Gets the value of the bodyStatement property.
     * 
     * @return
     *     possible object is
     *     {@link TStatement }
     *     
     */
    public TStatement getBodyStatement() {
        return bodyStatement;
    }

    /**
     * Sets the value of the bodyStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStatement }
     *     
     */
    public void setBodyStatement(TStatement value) {
        this.bodyStatement = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
