/*
 * generated by Xtext
 */
package nl.esi.poosl.xtext;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;

import nl.esi.poosl.PooslPackage;

/**
 * Initialization support for running Xtext languages without equinox extension
 * registry
 */
public class PooslStandaloneSetup extends PooslStandaloneSetupGenerated {

	public static void doSetup() {
		new PooslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.esi.nl/comma/actions/Actions")) {
			EPackage.Registry.INSTANCE.put("http://poosl.esi.nl/poosl/3.0.0", PooslPackage.eINSTANCE);
		}

		super.register(injector);
	}
}
