/*
 * generated by Xtext 2.12.0
 */
package nl.esi.poosl.xtext.validation;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class PooslValidator extends PooslJavaValidatorUniqueIdentifiers {
}
